apiVersion: v1
kind: Service
metadata:
  name: tomcat-service
  namespace: my-namespace  # Specify the same namespace
spec:
  selector:
    app: tomcat
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
