piVersion: v1
kind: Service
metadata:
  name: tomcat-service
spec:
 # type: NodePort  # Add this line to specify the service type
  selector:
    app: tomcat
  ports:
    - protocol: TCP
      port: 80         # Port exposed by the service
      targetPort: 8080 # Port on the container
      nodePort: 31122  # Node port (optional, if you want to specify it)

